name: Publish
on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: windows-latest
    name: Publish

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Install dependencies
      run: pnpm install

    - name: Publish to npm
      env:
        GH_TOKEN: ${{ github.token }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm publish
