name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest
    name: Publish

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest

    - name: Install dependencies
      run: pnpm install

    - name: Publish to npm
      env:
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        RELEASE_TAG: ${{ github.event.release.prerelease && 'next' || 'latest' }}
      run: npm publish --tag $RELEASE_TAG
